services:
  jupyter:
    container_name: jupyter
    build: ./builder
    ports:
      - 8888:8888
    volumes:
      - ./env.yml:/home/jovyan/env.yml
      - ./work:/home/jovyan/work/
      - ./hooks/:/usr/local/bin/before-notebook.d/
